lexik_jwt_authentication:
    # --- Clés de signature/vérification ---
    # La clé privée (pour signer les tokens)
    secret_key: "%env(resolve:JWT_PRIVATE_KEY)%"

    # La clé publique (pour vérifier les tokens)
    public_key: "%env(resolve:JWT_PUBLIC_KEY)%"

    # --- Gestion du mot de passe de la clé ---
    # S'assurer que c'est une chaîne vide si aucune passphrase n'a été utilisée
    pass_phrase: ""

    # --- Options du Token ---
    # Durée de vie du token (Récupère la valeur dans .env.local)
    token_ttl: "%env(int:JWT_TOKEN_TTL)%"

    # Champ utilisé pour identifier l'utilisateur (maintenant 'user_id_claim')

    user_id_claim: email
