controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# ðŸ”‘ AJOUTER CETTE DÃ‰CLARATION MANUELLE DE LA ROUTE LOGIN_CHECK
api_login_check:
    path: /api/login_check
    methods: ["POST"]
    # Ceci est le contrÃ´leur interne que Symfony utilise pour gÃ©rer le json_login.
    controller: symfony_security.controller.security_json_login_check
