# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

parameters:
    # ajoute ici tes paramètres custom si besoin

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true # Automatically injects dependencies.
        autoconfigure: true # Automatically registers commands, event subscribers, etc.

    # === Décorateur OpenAPI Platform pour ajouter le BearerAuth JWT ===
    App\OpenApi\OpenApiFactory:
        decorates: "api_platform.openapi.factory"
        arguments: ['@App\OpenApi\OpenApiFactory.inner']
        public: false

    # makes classes in src/ available as services
    App\:
        resource: "../src/"
